import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const publicDirectory = fileURLToPath(new URL("../public/", import.meta.url));
const canonicalOrigin = "https://www.simplemanplumbing.net";

function escapeForRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function readMetaContent(html, attribute, value) {
  const tag = new RegExp(
    `<meta\\s+[^>]*${attribute}=["']${escapeForRegex(value)}["'][^>]*>`,
    "i",
  ).exec(html)?.[0];
  const content = tag && /content=(["'])([\s\S]*?)\1/i.exec(tag)?.[2];
  return content?.replace(/&mdash;/g, "—") ?? "";
}

function normalizeText(value) {
  return value
    .replace(/&amp;/gi, "&")
    .replace(/&mdash;/gi, "—")
    .replace(/&ndash;/gi, "–")
    .replace(/&middot;/gi, "·")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&rsquo;|&lsquo;/gi, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function isNoindex(html) {
  return /<meta\s+[^>]*name=["']robots["'][^>]*content=["'][^"']*noindex/i.test(html);
}

function visibleText(html) {
  return html
    .replace(/<!--([\s\S]*?)-->/g, "")
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/&(?:nbsp|mdash|ndash);/gi, " ")
    .replace(/\s+/g, " ");
}

function jsonLdObjects(html) {
  return [...html.matchAll(/<script\s+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]
    .map((match) => JSON.parse(match[1]));
}

function graphNodes(html) {
  return jsonLdObjects(html).flatMap((item) => item["@graph"] ?? [item]);
}

function includesType(node, expected) {
  return (Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]]).includes(expected);
}

function sitemapLocations(xml) {
  return [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((match) => match[1].trim());
}

function detailsFaqs(html) {
  return [...html.matchAll(/<details\b[^>]*>\s*<summary[^>]*>([\s\S]*?)<\/summary>\s*<div[^>]*>([\s\S]*?)<\/div>\s*<\/details>/gi)]
    .map((match) => ({ question: normalizeText(match[1].replace(/<[^>]+>/g, " ")), answer: normalizeText(match[2].replace(/<[^>]+>/g, " ")) }))
    .filter(({ question, answer }) => question && answer);
}

test("publishes crawlability resources that agree on the canonical site", async () => {
  const [robots, sitemap, llms, fullReference] = await Promise.all([
    readFile(path.join(publicDirectory, "robots.txt"), "utf8"),
    readFile(path.join(publicDirectory, "sitemap.xml"), "utf8"),
    readFile(path.join(publicDirectory, "llms.txt"), "utf8"),
    readFile(path.join(publicDirectory, "llms-full.txt"), "utf8"),
  ]);

  assert.match(robots, /^User-agent:\s*\*/mi);
  assert.match(robots, /^Allow:\s*\/\s*$/mi);
  assert.match(robots, new RegExp(`^Sitemap:\\s*${escapeForRegex(canonicalOrigin)}/sitemap\\.xml\\s*$`, "mi"));
  assert.match(robots, /Allow:\s*\/llms\.txt/i);
  assert.match(sitemap, /<urlset\b[^>]*sitemaps\.org\/schemas\/sitemap\/0\.9/i);
  assert.match(llms, /^# Simple Man Plumbing\s*$/m);
  assert.match(llms, new RegExp(escapeForRegex(canonicalOrigin)));
  assert.match(fullReference, /Generated by scripts\/generate-ai-discovery\.mjs/);
  assert.match(fullReference, /Canonical page: https:\/\/www\.simplemanplumbing\.net\/flood-prevention-sump-pumps\.html/);

  for (const userAgent of ["GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "PerplexityBot", "Google-Extended"]) {
    assert.match(robots, new RegExp(`^User-agent:\\s*${escapeForRegex(userAgent)}\\s*$`, "mi"));
  }
});

test("applies a persisted light or dark theme across every public page", async () => {
  const [themeScript, styles, files] = await Promise.all([
    readFile(path.join(publicDirectory, "tvds.js"), "utf8"),
    readFile(path.join(publicDirectory, "styles.css"), "utf8"),
    readdir(publicDirectory),
  ]);

  assert.match(themeScript, /localStorage\.getItem\(THEME_KEY\)/);
  assert.match(themeScript, /localStorage\.setItem\(THEME_KEY, next\)/);
  assert.match(themeScript, /className = 'theme-toggle'/);
  assert.match(styles, /html\[data-theme="light"\]/);

  const deviceStyles = await readFile(path.join(publicDirectory, "tvds.css"), "utf8");
  assert.match(deviceStyles, /html\[data-theme="light"\] \.tvds-bottomnav \{ background:/, "light mode must give mobile navigation its own light surface");
  assert.match(deviceStyles, /html\[data-theme="light"\] \.tvds-bottomnav a \{ color:/, "light mode mobile navigation labels must remain visible");
  assert.match(styles, /--overlay:\s+rgba\(255,253,248,.82\)/, "light mode must define a matching overlay surface");
  assert.match(styles, /\.air-hero \.figure-tag[^}]*background: var\(--overlay\)/, "hero image tags must use the shared theme surface");
  assert.match(styles, /\.split \.figure-overlay[^}]*background: var\(--overlay-strong\)/, "split-image overlays must use the shared theme surface");
  assert.match(styles, /\.air-gallery figcaption[^}]*background: var\(--overlay\)/, "gallery labels must use the shared theme surface");
  assert.match(deviceStyles, /\.tvds-switch[^}]*background: var\(--overlay-strong\)/, "layout-preview controls must use the shared theme surface");

  for (const file of files.filter((file) => file.endsWith(".html"))) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    assert.match(html, /<script src="tvds\.js" defer><\/script>/, `${file} must load the shared theme controller`);
  }
});

test("makes storm and sump-pump help prominent from the homepage", async () => {
  const home = await readFile(path.join(publicDirectory, "index.html"), "utf8");

  assert.match(visibleText(home), /Water getting where it shouldn/i);
  assert.match(visibleText(home), /wet basement, sewer-backup concern, no-water issue, or sump-pump problem/i);
  assert.match(visibleText(home), /Four practical places to start before the next downpour/i);
  for (const topic of ["Test the whole sump-pump cycle", "Keep discharge water away", "Check the water coming from above", "Plan for the failure point"]) {
    assert.match(visibleText(home), new RegExp(topic, "i"));
  }
  assert.match(home, /href=["']tel:7658608667["']/i);
  assert.match(home, /href=["']flood-prevention-sump-pumps\.html["']/i);
});

test("sitemap covers every public HTML page exactly once", async () => {
  const [files, sitemap] = await Promise.all([
    readdir(publicDirectory),
    readFile(path.join(publicDirectory, "sitemap.xml"), "utf8"),
  ]);
  const indexableFiles = [];
  for (const file of files.filter((entry) => entry.endsWith(".html") && entry !== "404.html")) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    if (!isNoindex(html)) indexableFiles.push(file);
  }
  const expectedLocations = new Set(
    indexableFiles.map((file) => (file === "index.html" ? `${canonicalOrigin}/` : `${canonicalOrigin}/${file}`)),
  );
  const locations = sitemapLocations(sitemap);

  assert.equal(new Set(locations).size, locations.length, "sitemap URLs must not be duplicated");
  assert.deepEqual(new Set(locations), expectedLocations);

  for (const location of locations) {
    assert.ok(location.startsWith(`${canonicalOrigin}/`), `${location} must use the canonical origin`);
    const pathname = new URL(location).pathname;
    const file = pathname === "/" ? "index.html" : pathname.slice(1);
    assert.ok(files.includes(file), `${location} must resolve to a public file`);
  }

  for (const file of files.filter((candidate) => candidate.endsWith(".html"))) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    assert.doesNotMatch(html, /href=["']index\.html["']/i, `${file} must link to the canonical homepage route`);
  }

  for (const url of sitemap.matchAll(/<url>\s*<loc>[^<]+<\/loc>\s*<lastmod>([^<]+)<\/lastmod>/g)) {
    assert.match(url[1], /^\d{4}-\d{2}-\d{2}$/, "every sitemap entry must have a valid last-modified date");
  }
});

test("each location page names its represented city in content, metadata, and JSON-LD", async () => {
  const files = (await readdir(publicDirectory))
    .filter((file) => file.startsWith("plumber-") && file.endsWith(".html"))
    .sort();

  assert.ok(files.length > 0, "at least one location page is required");

  for (const file of files) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    const title = /<title>([\s\S]*?)<\/title>/i.exec(html)?.[1] ?? "";
    const city = graphNodes(html).find((node) => includesType(node, "Service"))?.areaServed?.name;

    assert.ok(city, `${file} must expose a represented city in its Service schema`);
    assert.match(title, new RegExp(escapeForRegex(city.replace("the ", "")), "i"), `${file} title must identify its represented city`);
    const searchableCity = city.replace("the ", "");
    assert.match(visibleText(html), new RegExp(`\\b${escapeForRegex(searchableCity)}\\b`, "i"), `${file} must mention ${city} in visible content`);
    assert.match(readMetaContent(html, "name", "description"), new RegExp(`\\b${escapeForRegex(searchableCity)}\\b`, "i"), `${file} description must mention ${city}`);
    assert.match(readMetaContent(html, "property", "og:title"), new RegExp(`\\b${escapeForRegex(searchableCity)}\\b`, "i"), `${file} Open Graph title must mention ${city}`);
    assert.match(readMetaContent(html, "property", "og:description"), new RegExp(`\\b${escapeForRegex(searchableCity)}\\b`, "i"), `${file} Open Graph description must mention ${city}`);

    const structuredData = graphNodes(html);
    assert.ok(
      structuredData.some(
        (item) =>
          includesType(item, "Service") &&
          item.areaServed?.["@type"] === "City" &&
          item.areaServed?.name === city,
      ),
      `${file} must expose ${city} as a Service area in the JSON-LD graph`,
    );
    assert.match(
      html,
      /href=["']flood-prevention-sump-pumps\.html["']/i,
      `${file} must connect the local page to the flood-prevention guide`,
    );
    assert.match(
      visibleText(html),
      /(?:flood|sump pump|wet basement|sewer backup)/i,
      `${file} must give local visitors a visible flood-readiness path`,
    );
  }
});

test("keeps every coverage-map pin visually distinct", async () => {
  const areas = await readFile(path.join(publicDirectory, "areas.html"), "utf8");
  const pins = [...areas.matchAll(/<g class="map-pin" data-city="([^"]+)"><circle cx="([\d.]+)" cy="([\d.]+)" r="(?:10|6)" class="pin-anchor"/g)]
    .map((match) => ({ city: match[1], x: Number(match[2]), y: Number(match[3]) }));

  assert.equal(pins.length, 11, "the coverage map must plot each service area once");
  assert.equal(new Set(pins.map((pin) => `${pin.x},${pin.y}`)).size, pins.length, "map pin coordinates must not be duplicated");
  for (const [index, pin] of pins.entries()) {
    for (const other of pins.slice(index + 1)) {
      const distance = Math.hypot(pin.x - other.x, pin.y - other.y);
      assert.ok(distance >= 30, `${pin.city} and ${other.city} pins must remain separated`);
    }
  }
  assert.equal((areas.match(/class="pin-leader"/g) ?? []).length, pins.length, "every coverage pin must have a leader line to its separate label");
});

test("uses one cross-linked JSON-LD graph and disciplined metadata on every public page", async () => {
  const files = (await readdir(publicDirectory)).filter((file) => file.endsWith(".html"));

  for (const file of files) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    if (isNoindex(html)) continue;
    const graphs = jsonLdObjects(html);
    assert.equal(graphs.length, 1, `${file} must have one JSON-LD block`);
    assert.ok(Array.isArray(graphs[0]["@graph"]), `${file} JSON-LD must use @graph`);
    assert.ok(graphNodes(html).some((node) => includesType(node, "WebSite")), `${file} must describe the website`);
    assert.ok(graphNodes(html).some((node) => includesType(node, "BreadcrumbList")), `${file} must include breadcrumbs`);

    const expectedCanonical = file === "index.html" ? `${canonicalOrigin}/` : `${canonicalOrigin}/${file}`;
    const canonical = /<link\s+[^>]*rel=["']canonical["'][^>]*href=["']([^"']+)["']/i.exec(html)?.[1] ?? "";
    assert.equal(canonical, expectedCanonical, `${file} must have one self-referencing canonical URL`);

    const title = normalizeText(/<title>([\s\S]*?)<\/title>/i.exec(html)?.[1] ?? "");
    assert.ok(title.length > 0 && title.length <= 60, `${file} title must be present and 60 characters or fewer`);
    assert.equal((title.match(/Simple Man Plumbing/gi) ?? []).length, 1, `${file} title must name the brand exactly once`);

    const description = normalizeText(readMetaContent(html, "name", "description"));
    assert.ok(description.length > 0 && description.length <= 155, `${file} description must be present and 155 characters or fewer`);
    assert.equal(normalizeText(readMetaContent(html, "property", "og:title")), title, `${file} Open Graph title must match the page title`);
    assert.equal(normalizeText(readMetaContent(html, "name", "twitter:title")), title, `${file} Twitter title must match the page title`);
    assert.equal(normalizeText(readMetaContent(html, "property", "og:description")), description, `${file} Open Graph description must match the page description`);
    assert.equal(normalizeText(readMetaContent(html, "name", "twitter:description")), description, `${file} Twitter description must match the page description`);

    const webPage = graphNodes(html).find((node) => includesType(node, "WebPage"));
    assert.equal(normalizeText(webPage?.name ?? ""), title, `${file} WebPage name must match the page title`);
    assert.equal(normalizeText(webPage?.description ?? ""), description, `${file} WebPage description must match the page description`);

    const organization = graphNodes(html).find((node) => includesType(node, "Organization"));
    assert.ok(!Object.hasOwn(organization ?? {}, "priceRange"), `${file} must not expose unapproved price ranges in search markup`);
    const person = graphNodes(html).find((node) => includesType(node, "Person"));
    assert.ok(Array.isArray(person?.knowsAbout) && person.knowsAbout.length > 0, `${file} must identify the named plumber's supported expertise`);
  }

  for (const file of ["index.html", "services.html", "areas.html", "about.html", "contact.html", "flood-prevention-sump-pumps.html"]) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    const title = normalizeText(/<title>([\s\S]*?)<\/title>/i.exec(html)?.[1] ?? "");
    assert.match(title, /Indianapolis/i, `${file} must make its Indianapolis relevance explicit in the title`);
  }
});

test("keeps the flood guide and recovery path machine-readable", async () => {
  const [floodHtml, servicesHtml, notFoundHtml, sitemap] = await Promise.all([
    readFile(path.join(publicDirectory, "flood-prevention-sump-pumps.html"), "utf8"),
    readFile(path.join(publicDirectory, "services.html"), "utf8"),
    readFile(path.join(publicDirectory, "404.html"), "utf8"),
    readFile(path.join(publicDirectory, "sitemap.xml"), "utf8"),
  ]);

  const floodNodes = graphNodes(floodHtml);
  const floodService = floodNodes.find((node) => includesType(node, "Service"));
  assert.ok(floodService, "the flood guide must identify its service topic");
  assert.equal(floodService.areaServed?.length, 11, "the flood guide must connect to every represented service area");
  const floodOrganization = floodNodes.find((node) => includesType(node, "Organization"));
  assert.equal(floodOrganization?.areaServed?.length, 11, "the flood guide organization must use the shared service-area list");
  const floodPerson = floodNodes.find((node) => includesType(node, "Person"));
  assert.equal(floodPerson?.hasCredential?.identifier, "PC12300114", "the flood guide must retain the verified individual credential");
  const article = floodNodes.find((node) => includesType(node, "BlogPosting"));
  assert.ok(article, "the flood guide must identify its article content");
  assert.match(article.dateModified, /^\d{4}-\d{2}-\d{2}$/);
  assert.ok(floodNodes.some((node) => includesType(node, "FAQPage")), "the flood guide FAQ must be structured");
  for (const phrase of ["sump pump", "check valve", "discharge", "backwater valve"]) {
    assert.match(visibleText(floodHtml), new RegExp(phrase, "i"), `the flood guide must visibly cover ${phrase}`);
  }

  assert.match(visibleText(servicesHtml), /Last updated:\s*August 17, 2026/i);
  assert.ok(!graphNodes(servicesHtml).some((node) => includesType(node, "OfferCatalog")), "services must not expose unapproved price offers in search markup");

  assert.match(notFoundHtml, /<meta name="robots" content="noindex, follow">/i);
  for (const route of ["/", "services.html", "areas.html", "flood-prevention-sump-pumps.html"]) {
    assert.match(notFoundHtml, new RegExp(`href=["']${escapeForRegex(route)}["']`, "i"), `404 page must link to ${route}`);
  }
  assert.doesNotMatch(sitemap, /404\.html/, "the noindex recovery page must not enter the sitemap");
});

test("keeps FAQ and article structured data synchronized with visible page content", async () => {
  const files = (await readdir(publicDirectory)).filter((file) => file.endsWith(".html"));

  for (const file of files) {
    const html = await readFile(path.join(publicDirectory, file), "utf8");
    const nodes = graphNodes(html);
    const faqPage = nodes.find((node) => includesType(node, "FAQPage"));
    const visibleFaqs = detailsFaqs(html);
    if (faqPage) {
      const structuredFaqs = (faqPage.mainEntity ?? []).map((entry) => ({
        question: normalizeText(entry.name ?? ""),
        answer: normalizeText(entry.acceptedAnswer?.text ?? ""),
      }));
      assert.deepEqual(structuredFaqs, visibleFaqs, `${file} FAQ schema must exactly match its visible details`);
    } else {
      assert.equal(visibleFaqs.length, 0, `${file} must not show a FAQ block without matching FAQ schema`);
    }

    for (const image of html.matchAll(/<img\b[^>]*>/gi)) {
      assert.match(image[0], /\balt=["'][^"']+["]/, `${file} images must have descriptive alt text`);
    }
  }

  const floodHtml = await readFile(path.join(publicDirectory, "flood-prevention-sump-pumps.html"), "utf8");
  const article = graphNodes(floodHtml).find((node) => includesType(node, "BlogPosting"));
  assert.ok(article, "the flood guide must retain article schema");
  const visibleHeadline = normalizeText(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i.exec(floodHtml)?.[1]?.replace(/<[^>]+>/g, " ") ?? "");
  assert.equal(normalizeText(article.headline), visibleHeadline, "article headline must be visible as the H1");
  assert.equal(normalizeText(article.description), normalizeText(readMetaContent(floodHtml, "name", "description")), "article description must match the page description");
  assert.match(article.wordCount, /^\d+$/, "article word count must be numeric");
});
